version: '3'
services:

  generate_dataset:
    build: ./generate_dataset
    command: "python app.py"
    volumes:
      - ./data:/data
      - ./generate_dataset/app.py:/app/app.py
  
  generate_dataset224:
    build: ./generate_dataset
    command: "python app_224.py"
    volumes:
      - ./data:/data
      - ./generate_dataset/app_224.py:/app/app_224.py

  train:
    build: ./train
    volumes:
      - ./data:/data
      - ./train/app.py:/app/app.py
