version: '3'
services:

  generate_dataset:
    build: ./generate_dataset
    command: "python app.py"
    volumes:
      - ./data:/data
      - ./generate_dataset/app.py:/app/app.py
  
  generate_dataset224:
    build: ./generate_dataset
    command: "python app_224.py"
    volumes:
      - ./data:/data
      - ./generate_dataset/app_224.py:/app/app_224.py

  cnn:
    build: ./train
    command: "python cnn.py"
    volumes:
      - ./data:/data
      - ./models:/models
      - ./train/cnn.py:/app/cnn.py
  
  vgg16_transfer:
    build: ./train
    command: "python vgg16_transfer.py"
    volumes:
      - ./data:/data
      - ./models:/models
      - ./train/vgg16_transfer.py:/app/vgg16_transfer.py
  
  predict:
    build: ./predict
    entrypoint: "python app.py"
    volumes:
      - ./data:/data
      - ./data/tests:/app/tests
      - ./models:/models
      - ./predict/app.py:/app/app.py
